### PR TITLE
Feat/cloud run launcher examples

### PR DESCRIPTION
**Pull request by baumann-t**
Adapted the example to work with multiple code locations (not functional yet)

### CODE REVIEW

**Comment by baumann-t** [comment]
@timchap, I have adapted my example to work with multiple code locations and your cloud run launcher.
I am able to launch a specific cloud run job from both my VM and locally (through `dagster dev`), but the job does not execute properly.

I have this error :

> dagster._core.errors.DagsterImportError: Encountered ImportError: `No module named 'pipeline1'` while importing module pipeline1. Local modules were resolved using the working directory `/pipeline1`. If another working directory should be used, please explicitly specify the appropriate path using the `-d` or `--working-directory` for CLI based targets or the `working_directory` configuration option for workspace targets. 

It's my first time using code locations, so I assume it is related to the way I build my docker images. Could you please have a look and see if you can spot my mistake?

Let me know if you have any questions or comments regarding my implementation.

Thanks

**Comment by baumann-t** [comment]
Hello @timchap,

I found the solution to my problem. It was related to local module installation and a wrong path for DAGSTER_HOME ([detailed here](https://discuss.dagster.io/t/2594846/hello-i-m-running-into-a-modulenotfounderror-no-module-named)).

My PR is ready for review.

Thanks!

**Comment by timchap** [comment]
Sorry, had a busy few days. Awesome, thanks! Will check it out and test on my side this evening.

**Comment by timchap** [comment]
Looks good, I just have one question about your deployment. How do you recommend to host the PG instance for the example? In some ways the "easiest" option would be Cloud SQL, but this would generally require a few tweaks to the deployment scripts as far as I can tell (e.g. [to proxy traffic between Cloud Run and the instance](https://cloud.google.com/sql/docs/mysql/connect-run#command-line), or by deploying the Cloud Run Job and SQL instance to a common VPC).

Maybe you have an easier method though?

**Comment by baumann-t** [comment]
Thanks for the review!

For this example, I simply created a Cloud SQL instance with a public IP address and allowed all traffic to the instance (0.0.0.0/0). While this approach is not recommended for production, it served the purpose of the example.

For a more robust solution, we would indeed need to implement the measures you mentioned. Additionally, I think it would be possible to add a [Serverless VPC Access connector](https://cloud.google.com/run/docs/configuring/vpc-connectors#create-connector) for Cloud Run and allow traffic from the connector to the SQL instance.

From my understanding, we could explain the different available approaches for the SQL instance in the documentation for the example without actually implementing them. We could consult [garethbrickman](https://github.com/garethbrickman) on the other PR to confirm if that's the recommended approach.

**Comment by timchap** [comment]
Ok great. Makes sense, I agree it's an acceptable solution for the example :+1:

**Pull request merged**
